### ISSUE TITLE
Bug: changing language from fa to en realtime not working

### ISSUE THREAD

**Issue by farhadggu** [ijavad805/react-datepicker#2]
I setup a toggle button for changing lang of datepicker
when I changing from "fa" to "en" without refreshing datepicker not working
I should  refresh the project to work

**Comment by ijavad805** [comment]
thanks to you for reporting this issue, I will fix it on a pull request, but if you are in a hurry, you can use this code to make it work
`
const [ lang, setLang ] = useState("en");

return (
       <>
              {lang === "en"  ? <Datepicker lang={"en"}/> : <Datepicker lang={"fa"} />}
       </>
)
`
