### ISSUE TITLE
Resetting Datepicker Value: Utilizing an API

### ISSUE THREAD

**Issue by saahandgh** [ijavad805/react-datepicker#26]
I need an API that allows resetting the value of the datepicker.

I appreciate your help

**Comment by ijavad805** [comment]
Hello dear Sahand, apologies for the delayed response.
Does #27 solve your issue? Inputs now have a clear button starting from version 2.2.14+. Additionally, passing `null` or `undefined` as the value should clear the input. By default, this behavior is true, but you can disable it with `allowClear={false}`

**Comment by saahandgh** [comment]
thanks for your response. 🙂
