### ISSUE TITLE
how to clear input?

### ISSUE THREAD

**Issue by erfanpaslar** [ijavad805/react-datepicker#27]
iv'e tried 

```
footer={(moment: any, setValue: any) => {
  return (
      <button
        onClick={() => {
          if (setValue) setValue(null);
        }}>
        clear
      </button>
  );
}}
```

but it does not work

**Comment by ijavad805** [comment]
Hello there, you are right. Today I will create a PR for this issue. Isn't that too much work

**Comment by erfanpaslar** [comment]
WOW that was fast
I've worked around it by selecting the input and setting the value to "" manually but JS selectors, but it's very messy.
Thanks for the update. I appreciate it.
